// <auto-generated />
using System;
using APIQuanLyCuaHang.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIQuanLyCuaHang.Migrations
{
    [DbContext(typeof(QuanLyCuaHangContext))]
    [Migration("20250331023139_CreateTableGioHangCTCombo")]
    partial class CreateTableGioHangCTCombo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Ban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("BAN", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Cakip", b =>
                {
                    b.Property<int>("MaCaKip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCaKip"));

                    b.Property<DateTime>("GioBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("GioKetThuc")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SoNguoiHienTai")
                        .HasColumnType("int");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.HasKey("MaCaKip")
                        .HasName("PK__CAKIP__68C49E4C467ECFEF");

                    b.ToTable("CAKIP", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Chitietcombo", b =>
                {
                    b.Property<int>("MaCombo")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongSp")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongSP");

                    b.HasKey("MaCombo", "MaSp")
                        .HasName("PK__CHITIETC__020940946F0EEEE6");

                    b.HasIndex("MaSp");

                    b.ToTable("CHITIETCOMBO", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Chitietsanpham", b =>
                {
                    b.Property<int>("MaCtsp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtsp"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(11, 2)");

                    b.Property<string>("HuongVi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("MaCtsp")
                        .HasName("PK__CHITIETS__1E4FCECD83115908");

                    b.HasIndex("MaSp");

                    b.ToTable("CHITIETSANPHAM", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Chucvu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucVu"));

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("LuongCung")
                        .HasColumnType("decimal(11, 2)");

                    b.Property<decimal?>("LuongTheoGio")
                        .HasColumnType("decimal(11, 2)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MaChucVu")
                        .HasName("PK__CHUCVU__D4639533676EA44D");

                    b.ToTable("CHUCVU", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Combo", b =>
                {
                    b.Property<int>("MaCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCombo"));

                    b.Property<string>("Hinh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<float?>("PhanTramGiam")
                        .HasColumnType("real");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenCombo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCombo")
                        .HasName("PK__COMBO__C3EDBC78C31DA0C5");

                    b.ToTable("COMBO", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Cthoadon", b =>
                {
                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("MaCtsp")
                        .HasColumnType("int")
                        .HasColumnName("MaCTSP");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHd", "MaCtsp")
                        .HasName("PK__CTHOADON__E6C15A0CD99CD838");

                    b.HasIndex("MaCtsp");

                    b.ToTable("CTHOADON", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Danhmuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MaDanhMuc")
                        .HasName("PK__DANHMUC__B37508874C124C7E");

                    b.ToTable("DANHMUC", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.GioHangCTCombo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChiTietSanPhamMaCtsp")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GioHangId")
                        .HasColumnType("int");

                    b.Property<int>("MaCTSp")
                        .HasColumnType("int");

                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietSanPhamMaCtsp");

                    b.HasIndex("GioHangId");

                    b.ToTable("GioHangCTCombos");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Giohang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(11, 2)");

                    b.Property<int?>("MaCombo")
                        .HasColumnType("int")
                        .HasColumnName("MaComboNavigation");

                    b.Property<int?>("MaCtsp")
                        .HasColumnType("int")
                        .HasColumnName("MaCTSP");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__GIOHANG__3214EC27376B130B");

                    b.HasIndex("MaCombo");

                    b.HasIndex("MaCtsp");

                    b.HasIndex("MaKh");

                    b.ToTable("GIOHANG", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Hinhanh", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<int>("MaCtsp")
                        .HasColumnType("int")
                        .HasColumnName("MaCTSP");

                    b.Property<string>("TenHinhAnh")
                        .HasColumnType("text");

                    b.HasKey("MaHinhAnh")
                        .HasName("PK__HINHANH__A9C37A9BE6F7EFCA");

                    b.HasIndex("MaCtsp");

                    b.ToTable("HINHANH", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Hoadon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<DateTime?>("BatDauGiao")
                        .HasColumnType("datetime");

                    b.Property<string>("DiaChiNhanHang")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HinhThucTt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HinhThucTT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<decimal>("PhiVanChuyen")
                        .HasColumnType("decimal(11, 2)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("SDT")
                        .IsFixedLength();

                    b.Property<decimal>("TienGoc")
                        .HasColumnType("decimal(11, 2)");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHd")
                        .HasName("PK__HOADON__2725A6E0A656C6A7");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("HOADON", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Khachhang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("Cccd")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("CCCD")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .IsFixedLength();

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HinhDaiDien")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("char(255)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("Sdt")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("SDT")
                        .IsFixedLength();

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.Property<string>("TinhTrang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasDefaultValue("Đang hoạt động");

                    b.HasKey("MaKh")
                        .HasName("PK__KHACHHAN__2725CF1E85FFC142");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Lichsulamviec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LyDoNghi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaCaKip")
                        .HasColumnType("int");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgayThangNam")
                        .HasColumnType("date");

                    b.Property<double>("SoGioLam")
                        .HasColumnType("float");

                    b.Property<decimal?>("TongLuong")
                        .HasColumnType("decimal(11, 2)");

                    b.HasKey("Id")
                        .HasName("PK__LICHSULA__3214EC27C0159D37");

                    b.HasIndex("MaCaKip");

                    b.HasIndex("MaNv");

                    b.ToTable("LICHSULAMVIEC", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.MaCoupon", b =>
                {
                    b.Property<string>("MaCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("DonHangToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PhanTramGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongDaDung")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaCode");

                    b.ToTable("MaCoupons");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Nhanvien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"));

                    b.Property<string>("Cccd")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("CCCD")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("char(40)")
                        .IsFixedLength();

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("SDT")
                        .IsFixedLength();

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.Property<string>("TinhTrang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasDefaultValue("Đang hoạt động");

                    b.HasKey("MaNv")
                        .HasName("PK__NHANVIEN__2725D70A5E4858B0");

                    b.HasIndex("MaChucVu");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Refreshtoken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__REFRESHT__3214EC27AF9EE8AD");

                    b.ToTable("REFRESHTOKEN", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Sanpham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSp")
                        .HasName("PK__SANPHAM__2725081C40D91290");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Chitietcombo", b =>
                {
                    b.HasOne("APIQuanLyCuaHang.Models.Combo", "MaComboNavigation")
                        .WithMany("Chitietcombos")
                        .HasForeignKey("MaCombo")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETCO__MaCom__5441852A");

                    b.HasOne("APIQuanLyCuaHang.Models.Sanpham", "MaSpNavigation")
                        .WithMany("Chitietcombos")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETCO__MaSP__5535A963");

                    b.Navigation("MaComboNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Chitietsanpham", b =>
                {
                    b.HasOne("APIQuanLyCuaHang.Models.Sanpham", "MaSpNavigation")
                        .WithMany("Chitietsanphams")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETSAN__MaSP__4BAC3F29");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Cthoadon", b =>
                {
                    b.HasOne("APIQuanLyCuaHang.Models.Chitietsanpham", "MaCtspNavigation")
                        .WithMany("Cthoadons")
                        .HasForeignKey("MaCtsp")
                        .IsRequired()
                        .HasConstraintName("FK__CTHOADON__MaCTSP__5DCAEF64");

                    b.HasOne("APIQuanLyCuaHang.Models.Hoadon", "MaHdNavigation")
                        .WithMany("Cthoadons")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK__CTHOADON__MaHD__5CD6CB2B");

                    b.Navigation("MaCtspNavigation");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.GioHangCTCombo", b =>
                {
                    b.HasOne("APIQuanLyCuaHang.Models.Chitietsanpham", "ChiTietSanPham")
                        .WithMany("GioHangCTCombos")
                        .HasForeignKey("ChiTietSanPhamMaCtsp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIQuanLyCuaHang.Models.Giohang", "GioHang")
                        .WithMany("GioHangCTCombos")
                        .HasForeignKey("GioHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Giohang", b =>
                {
                    b.HasOne("APIQuanLyCuaHang.Models.Combo", "MaComboNavigation")
                        .WithMany("Giohangs")
                        .HasForeignKey("MaCombo")
                        .HasConstraintName("FK_GIOHANG_COMBO_MaComboNavigationMaCombo");

                    b.HasOne("APIQuanLyCuaHang.Models.Chitietsanpham", "MaCtspNavigation")
                        .WithMany("Giohangs")
                        .HasForeignKey("MaCtsp")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__GIOHANG__MaCTSP__6B24EA82");

                    b.HasOne("APIQuanLyCuaHang.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Giohangs")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__GIOHANG__MaKH__6A30C649");

                    b.Navigation("MaComboNavigation");

                    b.Navigation("MaCtspNavigation");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Hinhanh", b =>
                {
                    b.HasOne("APIQuanLyCuaHang.Models.Chitietsanpham", "MaCtspNavigation")
                        .WithMany("Hinhanhs")
                        .HasForeignKey("MaCtsp")
                        .IsRequired()
                        .HasConstraintName("FK__HINHANH__MaCTSP__4E88ABD4");

                    b.Navigation("MaCtspNavigation");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Hoadon", b =>
                {
                    b.HasOne("APIQuanLyCuaHang.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__MaKH__59063A47");

                    b.HasOne("APIQuanLyCuaHang.Models.Nhanvien", "MaNvNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__HOADON__MaNV__59FA5E80");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Lichsulamviec", b =>
                {
                    b.HasOne("APIQuanLyCuaHang.Models.Cakip", "MaCaKipNavigation")
                        .WithMany("Lichsulamviecs")
                        .HasForeignKey("MaCaKip")
                        .IsRequired()
                        .HasConstraintName("FK__LICHSULAM__MaCaK__656C112C");

                    b.HasOne("APIQuanLyCuaHang.Models.Nhanvien", "MaNvNavigation")
                        .WithMany("Lichsulamviecs")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__LICHSULAMV__MaNV__6477ECF3");

                    b.Navigation("MaCaKipNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Nhanvien", b =>
                {
                    b.HasOne("APIQuanLyCuaHang.Models.Chucvu", "MaChucVuNavigation")
                        .WithMany("Nhanviens")
                        .HasForeignKey("MaChucVu")
                        .HasConstraintName("FK__NHANVIEN__MaChuc__4222D4EF");

                    b.Navigation("MaChucVuNavigation");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Sanpham", b =>
                {
                    b.HasOne("APIQuanLyCuaHang.Models.Danhmuc", "MaDanhMucNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("MaDanhMuc")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAM__IsDelet__48CFD27E");

                    b.Navigation("MaDanhMucNavigation");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Cakip", b =>
                {
                    b.Navigation("Lichsulamviecs");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Chitietsanpham", b =>
                {
                    b.Navigation("Cthoadons");

                    b.Navigation("GioHangCTCombos");

                    b.Navigation("Giohangs");

                    b.Navigation("Hinhanhs");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Chucvu", b =>
                {
                    b.Navigation("Nhanviens");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Combo", b =>
                {
                    b.Navigation("Chitietcombos");

                    b.Navigation("Giohangs");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Danhmuc", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Giohang", b =>
                {
                    b.Navigation("GioHangCTCombos");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Hoadon", b =>
                {
                    b.Navigation("Cthoadons");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Khachhang", b =>
                {
                    b.Navigation("Giohangs");

                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Nhanvien", b =>
                {
                    b.Navigation("Hoadons");

                    b.Navigation("Lichsulamviecs");
                });

            modelBuilder.Entity("APIQuanLyCuaHang.Models.Sanpham", b =>
                {
                    b.Navigation("Chitietcombos");

                    b.Navigation("Chitietsanphams");
                });
#pragma warning restore 612, 618
        }
    }
}
